require 'set'
require 'choo_choo/edi_835/document'
require 'choo_choo/segments/amt'
require 'choo_choo/segments/bpr'
require 'choo_choo/segments/cas'
require 'choo_choo/segments/clp'
require 'choo_choo/segments/cur'
require 'choo_choo/segments/dtm'
require 'choo_choo/segments/ge'
require 'choo_choo/segments/gs'
require 'choo_choo/segments/iea'
require 'choo_choo/segments/isa'
require 'choo_choo/segments/lq'
require 'choo_choo/segments/lx'
require 'choo_choo/segments/mia'
require 'choo_choo/segments/moa'
require 'choo_choo/segments/n1'
require 'choo_choo/segments/n3'
require 'choo_choo/segments/n4'
require 'choo_choo/segments/nm1'
require 'choo_choo/segments/per'
require 'choo_choo/segments/plb'
require 'choo_choo/segments/qty'
require 'choo_choo/segments/rdm'
require 'choo_choo/segments/ref'
require 'choo_choo/segments/se'
require 'choo_choo/segments/st'
require 'choo_choo/segments/svc'
require 'choo_choo/segments/trn'
require 'choo_choo/segments/ts2'
require 'choo_choo/segments/ts3'
require 'choo_choo/edi_835/parser'

module EDI835
  UPIN                    = '1G'
  PAYER_ID                = '2U'
  STATE_NUMBER            = '0B'
  PAYEE_ID                = 'PQ'
  EIN                     = 'TJ'
  RENDERING_PROVIDER      = '82' 
  INSURED_OR_SUBSCRIBER   = 'IL'
  PATIENT                 = 'QC'
  CORRECTED_INSURED       = '74'
  CROSSOVER               = 'TT'
  DEDUCTIBLE              = '1'
  CO_INSURANCE            = '2'
  CO_PAYMENT              = '3'
  PERSON                  = '1'
  ORGANIZATION            = '2'
  PATIENT_RESPONSIBILITY  = 'PR'
  CHARGE_NUMBER           = '6R'

  PR_CODES                = Set.new([DEDUCTIBLE, CO_INSURANCE, CO_PAYMENT])
  WITHHOLD_CODES          = Set.new(%w{104 253 105 245 144})
end